eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #注册服务列表显示ip+端口
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://192.168.150.5:8762/eureka/
server:
  port: 8887


spring:
  application:
    name: boot-service-a
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: boot-service-a
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受（订阅）。
      name: dubbo
      port: 20881
    consumer:
      check: false
      filter: "tracing"
    reference:
      loadbalance: roundrobin #轮询机制
      #loadbalance: random #随机机制
      #loadbalance: leastactive #最少活跃调用数机制
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
    sender:
      type: web #向kafka发送trace信息
    service:
      name: boot-service-a