spring:
  application:
    name: service-demo-2
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8999